### ISSUE TITLE
Use Docker API to pull new images from registry

### ISSUE THREAD

**Issue by talevy** [untergeek/longshoreman#9]
docker api provides functionality to create image from registry

https://docs.docker.com/reference/api/docker_remote_api_v1.19/  

within `docker-api` ruby project:

https://github.com/swipely/docker-api/blob/master/lib/docker/image.rb#L105

**Comment by untergeek** [comment]
MAKE IT SO!

**Comment by talevy** [comment]
closing since this is probably not applicable with all the new docker versions and strategies
